version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    environment:
      RAILS_ENV: test
      NODE_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run: gem update bundler
      - run: yarn install --pure-lockfile
      - ruby/bundle-install
      - run: bin/rails db:test:prepare RAILS_ENV=test
      - run: bundle exec rspec